---

- name: Copy backgrounds
  copy:
    src: "{{ playbook_dir }}/backgrounds/"
    dest: "{{ ansible_user_dir}}/.local/share/backgrounds/"

- name: Change the background 
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file://{{ ansible_user_dir}}/.local/share/backgrounds/abstract.png'"

- name: Enable dark theme
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Enable night light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"

- name: Make app switcher available on the current workspace only
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"

- name: Remember recently used files for only 30 days
  dconf:
    key: "/org/gnome/desktop/privacy/recent-files-max-age"
    value: "30"

- name: Remove old temporary files
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-temp-files"
    value: "true"

- name: Remove old trash files
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-trash-files"
    value: "true"

- name: Delete old temporary & trash files after 30 days
  dconf:
    key: "/org/gnome/desktop/privacy/old-files-age"
    value: "30"

- name: Enable automatic timezone
  dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"

- name: 24-hour clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

- name: Disable unnecessary search providers
  dconf:
    key: "/org/gnome/desktop/search-providers/disabled"
    value: "['org.gnome.Contacts.desktop', 'org.gnome.Boxes.desktop', 'org.gnome.clocks.desktop', 'org.gnome.Settings.desktop', 'org.gnome.Software.desktop', 'org.gnome.Terminal.desktop', 'org.mozilla.firefox.desktop']"

- name: Install GNOME Tweaks and Extensions
  package:
    name:
      - gnome-tweaks
      - gnome-extensions-app  
  become: true

- name: Center new windows
  dconf:
    key: "/org/gnome/mutter/center-new-windows"
    value: "true"

- name: Install GNOME extensions
  package:
    name:
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-blur-my-shell
  become: true

- name: Enable GNOME extensions
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['background-logo@fedorahosted.org', 'blur-my-shell@aunetx', 'caffeine@patapon.info']"

