---

- name: Configure rpm-ostree update settings
  ansible.builtin.template:
    src: templates/rpm-ostreed.conf.jinja2
    dest: /etc/rpm-ostreed.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo

- name: Copy flatpak-automatic-update service and timer files to host
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo
  loop:
    - flatpak-automatic.service
    - flatpak-automatic.timer

- name: Enable timer unit to update flatpak applicaitons
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - flatpak-automatic.timer
    - rpm-ostreed-automatic.timer

- name: Enable experimental bluetooth settings
  ansible.builtin.replace:
    path: /etc/bluetooth/main.conf
    regexp: '#Experimental = false'
    replace: 'Experimental = true'
  become: yes
  become_method: sudo

- name: Restart bluetooth service
  ansible.builtin.systemd_service:
    name: bluetooth
    state: restarted
    daemon_reload: true
  become: yes
  become_method: sudo

